### ISSUE TITLE
BungeeCord errors

### ISSUE THREAD

**Issue by Yavoroshko** [BlueTree242/AdvancedPlHide#9]
```java
[00:18:45 ERROR]: java.lang.NullPointerException: Cannot invoke "tk.bluetree242.advancedplhide.config.Config.dev_updatechecker()" because the return value of "tk.bluetree242.advancedplhide.PlatformPlugin.getConfig()" is null
[00:18:45 ERROR]:       at tk.bluetree242.advancedplhide.PlatformPlugin.updateCheck(PlatformPlugin.java:115)
[00:18:45 ERROR]:       at tk.bluetree242.advancedplhide.bungee.AdvancedPlHideBungee.lambda$performStartUpdateCheck$1(AdvancedPlHideBungee.java:96)
[00:18:45 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[00:18:45 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:18:45 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:18:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[00:18:45 ERROR] [AdvancedPlHide]: Could not check for updates

[00:20:10 ERROR]: [Protocolize] Exception caught in listener while sending packet net.md_5.bungee.protocol.packet.Commands
java.lang.NullPointerException: Cannot invoke "tk.bluetree242.advancedplhide.config.Config.remove_plugin_prefix()" because the return value of "tk.bluetree242.advancedplhide.PlatformPlugin.getConfig()" is null
        at tk.bluetree242.advancedplhide.CompleterModifier.handleCompleter(CompleterModifier.java:42) ~[?:?]
        at tk.bluetree242.advancedplhide.bungee.listener.packet.BungeePacketListener$CommandsListener.packetSend(BungeePacketListener.java:116) ~[?:?]
        at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.lambda$handleOutboundPacket$1(BungeeCordPacketListenerProvider.java:104) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.handleOutboundPacket(BungeeCordPacketListenerProvider.java:102) ~[?:?]
        at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:30) ~[?:?]
        at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:66) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:738) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.protocol.packet.Commands.handle(Commands.java:232) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:129) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:20:10 ERROR]: [Protocolize] Exception caught in listener while sending packet net.md_5.bungee.protocol.packet.Commands
java.lang.NullPointerException: Cannot invoke "tk.bluetree242.advancedplhide.config.Config.remove_plugin_prefix()" because the return value of "tk.bluetree242.advancedplhide.PlatformPlugin.getConfig()" is null
        at tk.bluetree242.advancedplhide.CompleterModifier.handleCompleter(CompleterModifier.java:42) ~[?:?]
        at tk.bluetree242.advancedplhide.bungee.listener.packet.BungeePacketListener$CommandsListener.packetSend(BungeePacketListener.java:116) ~[?:?]
        at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.lambda$handleOutboundPacket$1(BungeeCordPacketListenerProvider.java:104) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.handleOutboundPacket(BungeeCordPacketListenerProvider.java:102) ~[?:?]
        at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:30) ~[?:?]
        at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:66) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:738) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.protocol.packet.Commands.handle(Commands.java:232) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:129) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord-1.1.9.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:a902014:unknown]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by BlueTree242** [comment]
Make sure your config.yml is valid using a validator or if you don't know how send it here

**Comment by Yavoroshko** [comment]
# You should read this before doing anything with the plugin, to understand how stuff work: https://github.com/BlueTree242/AdvancedPlHide/wiki/
#Message to send when the player tries to run /plugins, bypass: plhide.command.use
pl_message: '&cWe won''t show you the plugin list for sure.'
#Removes the plugin:command from tabcompleter, it function better than spigot does it
remove_plugin_prefix: true

# https://github.com/BlueTree242/AdvancedPlHide/wiki/groups
groups:
  default:
    tabcomplete:
      - 'serverlistplus'
      - 'pl'
      - 'plugins'
      - 'version'
      - 'example1'
      - 'example2'


# If you disable this, we will not notify you of new dev builds but of new major or beta updates
dev_updatechecker: true

**Comment by Yavoroshko** [comment]
```
# You should read this before doing anything with the plugin, to understand how stuff work: https://github.com/BlueTree242/AdvancedPlHide/wiki/
#Message to send when the player tries to run /plugins, bypass: plhide.command.use
pl_message: '&cWe won''t show you the plugin list for sure.'
#Removes the plugin:command from tabcompleter, it function better than spigot does it
remove_plugin_prefix: true

# https://github.com/BlueTree242/AdvancedPlHide/wiki/groups
groups:
  default:
    tabcomplete:
      - 'serverlistplus'
      - 'pl'
      - 'plugins'
      - 'version'
      - 'example1'
      - 'example2'


# If you disable this, we will not notify you of new dev builds but of new major or beta updates
dev_updatechecker: true

```

**Comment by BlueTree242** [comment]
Yeah i just remembered its an old bug fixed in dev builds but my CI is down so give me time to build it myself

**Comment by Yavoroshko** [comment]
How long will it take? like days, weeks or months?

I don't want to push you, I'm just curious, because I want to comfugure my server already.

**Comment by BlueTree242** [comment]
a few minutes

**Comment by Yavoroshko** [comment]
Oh! Thank you for quick reply!

**Comment by BlueTree242** [comment]
np, please wait its building

**Comment by BlueTree242** [comment]
https://file.io/O8sAIVrWjwEz

**Comment by Yavoroshko** [comment]
It works! Thank you!

**Comment by BlueTree242** [comment]
np 👍

**Comment by BlueTree242** [comment]
For anyone reading this, development builds are normally available [here](https://ci.bluetree242.ml/job/AdvancedPlHide)
